services:
  - type: web
    name: habeshan-ecommerce
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install --legacy-peer-deps && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
